/*
 * This header is associated with GENERATED file
 * method_index.c .  The C file is generated by
 * tools/generate_method_table.py .
 *
 * The global method index is used during class loading to
 * aid in constructing class vtables.  The actual method
 * addresses are determined when the methods are loaded,
 * and depend on the order of loading as well as the length
 * of each method.  In the relocatable "object" code
 * (e.g., stored in a class file to be loaded), methods are
 * given indexes which can be mapped to entries in this
 * table to find the address at which the method code
 * has been stored in the vm code memory page.
 */

#ifndef TINY_VM_METHOD_INDEX_H
#define TINY_VM_METHOD_INDEX_H

#include "vm_core.h"

#define MAX_METHODS 1000

struct method_address_table_struct {
    char *method_name;
    vm_addr method_address;
};

extern int n_methods;
extern struct method_address_table_struct
        method_index[MAX_METHODS];



#endif //TINY_VM_METHOD_INDEX_H
