#!/bin/bash

POSITIONAL_ARGS=()
CLASSNAME=""
OUTFILE=""
while [[ $# -gt 0 ]]; do
  case $1 in
    -i|--input)
      INFILE="$2"
      shift # past argument
      shift # past value
      ;;
    -o|--output)
      OUTFILE="$2"
      shift # past argument
      shift # past value
      ;;
    -cn|--classname)
      CLASSNAME="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done
if [ "$CLASSNAME" == "" ]; then
    CLASSNAME="Main"
fi
if [ "$OUTFILE" == "" ]; then
    OUTFILE="Main.asm"
fi
python3 quack_parser.py -i "$INFILE" -o "${OUTFILE}" -cn "$CLASSNAME"

ret=$?
if [ $ret -eq 0 ]; then
    python3 assemble.py "${OUTFILE}" "OBJ/${CLASSNAME}.json"
fi
