#!/bin/bash

POSITIONAL_ARGS=()
CLASSNAME=""
while [[ $# -gt 0 ]]; do
  case $1 in
    -i|--input)
      INFILE="$2"
      shift # past argument
      shift # past value
      ;;
    -cn|--classname)
      CLASSNAME="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done
if [ "$CLASSNAME" == "" ]; then
    CLASSNAME="Main"
fi
rm 0_*.asm
classes=`python3 quack_parser.py -i "$INFILE" -cn "$CLASSNAME"`

ret=$?
if [ $ret -eq 0 ]; then
    for cls in $classes
    do
        python3 assemble.py "0_${cls}.asm" "OBJ/${cls}.json"
        ret=$?
        if [ $ret -ne 0 ]; then
            exit 1
        fi
    done
fi
