#!/bin/bash

POSITIONAL_ARGS=()
CLASSNAME=""
while [[ $# -gt 0 ]]; do
  case $1 in
    -i|--input)
      INFILE="$2"
      shift # past argument
      shift # past value
      ;;
    -cn|--classname)
      CLASSNAME="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done
if [ "$CLASSNAME" == "" ]; then
    CLASSNAME="Main"
fi


. ./quackc -i "$INFILE" -cn "$CLASSNAME"
if [ $ret -eq 0 ]; then
    ./bin/tiny_vm -L OBJ "$CLASSNAME"
fi